name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "20.x"
      - name: git config
        run: |
          git config user.name github-pages-deploy-action
          git config user.email github-pages-deploy-action@@users.noreply.github.com
          git remote set-url origin https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git
      - run: yarn install
      - run: yarn build
        env:
          VITE_GRAPHQL_ENDPOINT: https://us-east1-gitpop3.cloudfunctions.net/gitpop3-graphql
          VITE_SENTRY_DSN: https://46cd951350084768a0306d2c223f7805@o87984.ingest.sentry.io/5575586
      - run: yarn deploy
